export const TOP_TARGET_COMPANIES: string[] = [
  "Google",
  "Amazon",
  "Meta",
  "Apple",
  "Microsoft",
  "Netflix",
  "NVIDIA",
  "OpenAI",
  "Salesforce",
  "Adobe",
  "Uber",
  "Airbnb",
  "Stripe",
  "Coinbase",
  "Databricks",
  "Snowflake",
  "Palantir",
  "Atlassian",
  "Shopify",
  "Intuit",
  "Oracle",
  "Cisco",
  "LinkedIn",
  "Dropbox",
  "Zoom",
  "Twilio",
  "Block",
  "PayPal",
  "Robinhood",
  "DoorDash",
  "Instacart",
  "Pinterest",
  "Reddit",
  "Snap",
  "Lyft",
  "Asana",
  "Notion",
  "Canva",
  "Figma",
  "Miro",
  "HubSpot",
  "ServiceNow",
  "Workday",
  "Okta",
  "Datadog",
  "Cloudflare",
  "MongoDB",
  "Confluent",
  "Elastic",
  "GitHub",
  "GitLab",
  "Vercel",
  "Replit",
  "Anthropic",
  "Perplexity",
  "xAI",
  "Tesla",
  "Rivian",
  "SpaceX",
  "Anduril",
  "Northrop Grumman",
  "Lockheed Martin",
  "Boeing",
  "Raytheon",
  "JPMorgan Chase",
  "Goldman Sachs",
  "Morgan Stanley",
  "American Express",
  "Capital One",
  "Visa",
  "Mastercard",
  "BlackRock",
  "Bloomberg",
  "McKinsey & Company",
  "Boston Consulting Group",
  "Bain & Company",
  "Deloitte",
  "PwC",
  "EY",
  "KPMG",
  "Walmart",
  "Target",
  "Costco",
  "Procter & Gamble",
  "PepsiCo",
  "Coca-Cola",
  "Johnson & Johnson",
  "Pfizer",
  "Moderna",
  "Gilead",
  "AbbVie",
  "Merck",
  "UnitedHealth Group",
  "CVS Health",
  "Humana",
  "Intel",
  "AMD",
  "Qualcomm",
  "Broadcom",
  "Texas Instruments",
];

export const TOP_TARGET_COMPANY_ALIASES: Record<string, string> = {
  "alphabet": "Google",
  "alphabet inc": "Google",
  "google llc": "Google",
  "google inc": "Google",
  "amazon.com": "Amazon",
  "amazon inc": "Amazon",
  "meta platforms": "Meta",
  "facebook": "Meta",
  "facebook inc": "Meta",
  "microsoft corporation": "Microsoft",
  "apple inc": "Apple",
  "nvidia corporation": "NVIDIA",
  "jpmorgan": "JPMorgan Chase",
  "jpmorgan chase & co": "JPMorgan Chase",
  "goldman sachs group": "Goldman Sachs",
  "morgan stanley inc": "Morgan Stanley",
};

export const TOP_TARGET_COMPANY_LOGOS: Record<string, string> = {
  Google: "https://logo.clearbit.com/google.com",
  Amazon: "https://logo.clearbit.com/amazon.com",
  Meta: "https://logo.clearbit.com/meta.com",
  Apple: "https://logo.clearbit.com/apple.com",
  Microsoft: "https://logo.clearbit.com/microsoft.com",
  Netflix: "https://logo.clearbit.com/netflix.com",
  NVIDIA: "https://logo.clearbit.com/nvidia.com",
  OpenAI: "https://logo.clearbit.com/openai.com",
  Salesforce: "https://logo.clearbit.com/salesforce.com",
  Adobe: "https://logo.clearbit.com/adobe.com",
  Uber: "https://logo.clearbit.com/uber.com",
  Airbnb: "https://logo.clearbit.com/airbnb.com",
  Stripe: "https://logo.clearbit.com/stripe.com",
  Coinbase: "https://logo.clearbit.com/coinbase.com",
  Databricks: "https://logo.clearbit.com/databricks.com",
  Snowflake: "https://logo.clearbit.com/snowflake.com",
  Palantir: "https://logo.clearbit.com/palantir.com",
  Atlassian: "https://logo.clearbit.com/atlassian.com",
  Shopify: "https://logo.clearbit.com/shopify.com",
  Intuit: "https://logo.clearbit.com/intuit.com",
  Oracle: "https://logo.clearbit.com/oracle.com",
  Cisco: "https://logo.clearbit.com/cisco.com",
  LinkedIn: "https://logo.clearbit.com/linkedin.com",
  Dropbox: "https://logo.clearbit.com/dropbox.com",
  Zoom: "https://logo.clearbit.com/zoom.us",
  Twilio: "https://logo.clearbit.com/twilio.com",
  Block: "https://logo.clearbit.com/block.xyz",
  PayPal: "https://logo.clearbit.com/paypal.com",
  Robinhood: "https://logo.clearbit.com/robinhood.com",
  DoorDash: "https://logo.clearbit.com/doordash.com",
  Instacart: "https://logo.clearbit.com/instacart.com",
  Pinterest: "https://logo.clearbit.com/pinterest.com",
  Reddit: "https://logo.clearbit.com/reddit.com",
  Snap: "https://logo.clearbit.com/snap.com",
  Lyft: "https://logo.clearbit.com/lyft.com",
  Asana: "https://logo.clearbit.com/asana.com",
  Notion: "https://logo.clearbit.com/notion.so",
  Canva: "https://logo.clearbit.com/canva.com",
  Figma: "https://logo.clearbit.com/figma.com",
  Miro: "https://logo.clearbit.com/miro.com",
  HubSpot: "https://logo.clearbit.com/hubspot.com",
  ServiceNow: "https://logo.clearbit.com/servicenow.com",
  Workday: "https://logo.clearbit.com/workday.com",
  Okta: "https://logo.clearbit.com/okta.com",
  Datadog: "https://logo.clearbit.com/datadoghq.com",
  Cloudflare: "https://logo.clearbit.com/cloudflare.com",
  MongoDB: "https://logo.clearbit.com/mongodb.com",
  Confluent: "https://logo.clearbit.com/confluent.io",
  Elastic: "https://logo.clearbit.com/elastic.co",
  GitHub: "https://logo.clearbit.com/github.com",
  GitLab: "https://logo.clearbit.com/gitlab.com",
  Vercel: "https://logo.clearbit.com/vercel.com",
  Replit: "https://logo.clearbit.com/replit.com",
  Anthropic: "https://logo.clearbit.com/anthropic.com",
  Perplexity: "https://logo.clearbit.com/perplexity.ai",
  xAI: "https://logo.clearbit.com/x.ai",
  Tesla: "https://logo.clearbit.com/tesla.com",
  Rivian: "https://logo.clearbit.com/rivian.com",
  SpaceX: "https://logo.clearbit.com/spacex.com",
  Anduril: "https://logo.clearbit.com/anduril.com",
  "Northrop Grumman": "https://logo.clearbit.com/northropgrumman.com",
  "Lockheed Martin": "https://logo.clearbit.com/lockheedmartin.com",
  Boeing: "https://logo.clearbit.com/boeing.com",
  Raytheon: "https://logo.clearbit.com/rtx.com",
  "JPMorgan Chase": "https://logo.clearbit.com/jpmorganchase.com",
  "Goldman Sachs": "https://logo.clearbit.com/goldmansachs.com",
  "Morgan Stanley": "https://logo.clearbit.com/morganstanley.com",
  "American Express": "https://logo.clearbit.com/americanexpress.com",
  "Capital One": "https://logo.clearbit.com/capitalone.com",
  Visa: "https://logo.clearbit.com/visa.com",
  Mastercard: "https://logo.clearbit.com/mastercard.com",
  BlackRock: "https://logo.clearbit.com/blackrock.com",
  Bloomberg: "https://logo.clearbit.com/bloomberg.com",
  "McKinsey & Company": "https://logo.clearbit.com/mckinsey.com",
  "Boston Consulting Group": "https://logo.clearbit.com/bcg.com",
  "Bain & Company": "https://logo.clearbit.com/bain.com",
  Deloitte: "https://logo.clearbit.com/deloitte.com",
  PwC: "https://logo.clearbit.com/pwc.com",
  EY: "https://logo.clearbit.com/ey.com",
  KPMG: "https://logo.clearbit.com/kpmg.com",
  Walmart: "https://logo.clearbit.com/walmart.com",
  Target: "https://logo.clearbit.com/target.com",
  Costco: "https://logo.clearbit.com/costco.com",
  "Procter & Gamble": "https://logo.clearbit.com/pg.com",
  PepsiCo: "https://logo.clearbit.com/pepsico.com",
  "Coca-Cola": "https://logo.clearbit.com/coca-colacompany.com",
  "Johnson & Johnson": "https://logo.clearbit.com/jnj.com",
  Pfizer: "https://logo.clearbit.com/pfizer.com",
  Moderna: "https://logo.clearbit.com/modernatx.com",
  Gilead: "https://logo.clearbit.com/gilead.com",
  AbbVie: "https://logo.clearbit.com/abbvie.com",
  Merck: "https://logo.clearbit.com/merck.com",
  "UnitedHealth Group": "https://logo.clearbit.com/unitedhealthgroup.com",
  "CVS Health": "https://logo.clearbit.com/cvshealth.com",
  Humana: "https://logo.clearbit.com/humana.com",
  Intel: "https://logo.clearbit.com/intel.com",
  AMD: "https://logo.clearbit.com/amd.com",
  Qualcomm: "https://logo.clearbit.com/qualcomm.com",
  Broadcom: "https://logo.clearbit.com/broadcom.com",
  "Texas Instruments": "https://logo.clearbit.com/ti.com",
};
